export const GET_LOADING = "GET_LOADING";
export const GET_SUCCESS = "GET_SUCCESS";
export const GET_ERROR = "GET_ERROR";

export const CREATE_BLOG_LOADING = "CREATE_BLOG_LOADING";
export const CREATE_BLOG_SUCCESS = "CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_ERROR = "CREATE_BLOG_ERROR";

export const EDIT_BLOG_LOADING = "EDIT_BLOG_LOADING";
export const EDIT_BLOG_SUCCESS = "EDIT_BLOG_SUCCESS";
export const EDIT_BLOG_ERROR = "EDIT_BLOG_ERROR";

export const DELETE_BLOG_LOADING = "DELETE_BLOG_LOADING";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_ERROR = "DELETE_BLOG_ERROR";
